version: '3'
services:
  app:
    image: lenesrenzo/billing-app:1.0.4
    environment:
      NEXT_PUBLIC_SUPABASE_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRqamhveWZxbXdzdHJ5dmNnaHh5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzEyMTE4MTEsImV4cCI6MjA0Njc4NzgxMX0.kmSsgslHCatiTadkQJDiXQdN2PlBXeD5URt5PDATvCU
      NEXT_PUBLIC_SUPABASE_URL: https://tjjhoyfqmwstryvcghxy.supabase.co
      NEXT_PUBLIC_API_1_ACCESS_KEY: d4bdb9065a750ded77f73f32a8b1c13e189d30bf250cb92415570005ed284377
      NEXT_PUBLIC_API_1_SECRET_KEY: 1eb3df9a4ba40af2afa18470bf6adb385d13836cee063c56bb82f7411d40d802

      NEXT_PUBLIC_API_2_ACCESS_KEY: 97a071f03f6a753e8bb06b3347f21d58f75fa0ee3afb40f9680a9d88571075a2
      NEXT_PUBLIC_API_2_SECRET_KEY: c8e20c46d05d22edfe141af936d7932f09ce65d2c06e268cfbb0c2ad66fa1d2a

      NEXT_PUBLIC_API_3_ACCESS_KEY: 58554a8c7ab07b90c0bd6d4bdba7abb199894067c432d1eb79293ac63922747f
      NEXT_PUBLIC_API_3_SECRET_KEY: 5a776c1d9e2f63787b56ff0f190d89a769124621e256a8b9ec4f50e19894c94b

      NEXT_PUBLIC_API_4_ACCESS_KEY: 32afb54b1b94571d0cbefa9cf5a27b25f5ddf73e08aa564858cf0174c7ac0ab7
      NEXT_PUBLIC_API_4_SECRET_KEY: 793b140822cc45914e6cb98cccce56c365a7968a8585b325b8753a0b609b6de3

      NEXT_PUBLIC_API_5_ACCESS_KEY: a2bba7f769348915510663d43393b48466d74950ad010dc7a7fcbf5a5a19d11a
      NEXT_PUBLIC_API_5_SECRET_KEY: 6f976bd937c1aa21a513d002171bb4aabb2c083bdc579c12cac58caf8c31b77a

      NEXT_PUBLIC_API_6_ACCESS_KEY: e1c614af75aba09e444c3d1e0df36ad5f0d9f9b81c6f40002052449c0d648231
      NEXT_PUBLIC_API_6_SECRET_KEY: c18d39d6146e63d550120d3d4e5b333c2a5ce728b2ebe2f8b6394de8b157fc2e


    ports:
      - "3000:3000"